networks:
  tms_jar:
    driver: bridge

volumes:
  db_data:

services:
  nginx:
    container_name: "${COMPOSE_PROJECT_NAME}-nginx"
    image: cslant/dev-nginx
    volumes:
      - ./:/app
      - ./docker/logs:/var/log/nginx
      - ./docker/nginx/tms.uit.local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_HOST_HTTP_PORT:-80}:80"
    platform: ${PLATFORM:-linux/amd64}
    networks:
      - tms_jar
    depends_on:
      - spring_app
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mysql:8.0.32
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-tms_jar}
    networks:
      - tms_jar

  spring_app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: "${COMPOSE_PROJECT_NAME}-${APP_HOST}"
    ports:
      - "${SPRING_HOST_PORT}:${SPRING_LOCAL_HOST_PORT}"
    depends_on:
      - db
      - phpmyadmin
    networks:
      - tms_jar
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:-root}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:-root}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${COMPOSE_PROJECT_NAME}-phpmyadmin"
    platform: ${PLATFORM:-linux/amd64}
    restart: always
    ports:
      - "${PHPMYADMIN_PORT:-9024}:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 2048M
    networks:
      - tms_jar
