networks:
  tms_jar:
    driver: bridge

volumes:
  db_data:

services:
  nginx:
    container_name: "${COMPOSE_PROJECT_NAME}-nginx"
    image: cslant/dev-nginx
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./:/app
      - ./docker/logs:/var/log/nginx
    ports:
      - "${NGINX_HOST_HTTP_PORT:-80}:80"
    platform: ${PLATFORM:-linux/amd64}
    environment:
      - NGINX_HOST_NAME=${NGINX_HOST_NAME:-tms.uit.local}
    networks:
      - tms_jar
    depends_on:
      - db
      - spring_app
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mysql:8.0.32
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-tms}
    networks:
      - tms_jar

  spring_app:
    build: .
    container_name: "${COMPOSE_PROJECT_NAME}-app"
    ports:
      - "${SPRING_APP_HOST_PORT:-8085}:8080"
    depends_on:
      - db
    networks:
      - tms_jar
    environment:
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE:-tms}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:-root}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:-root}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      NGINX_HOST_NAME: ${NGINX_HOST_NAME:-tms.uit.local}
      NGINX_HOST_HTTP_PORT: ${NGINX_HOST_HTTP_PORT:-8095}
      SPRING_HOST_PORT: ${SPRING_HOST_PORT:-8085}
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${COMPOSE_PROJECT_NAME}-phpmyadmin"
    platform: ${PLATFORM:-linux/amd64}
    restart: always
    ports:
      - "${PHPMYADMIN_PORT:-9024}:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 2048M
    networks:
      - tms_jar
