# Use a Maven image
FROM maven:3.9.6-eclipse-temurin-17 AS builder

# Set working directory
WORKDIR /app

# Copy only pom.xml first and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

# Now copy the rest of your code
COPY . .

# Compile your project
CMD ["./mvnw", "clean", "spring-boot:run"]