# Dockerfile.dev
FROM eclipse-temurin:17-jdk

# Install Maven
RUN apt-get update && \
    apt-get install -y maven && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

# Optional: install Maven Wrapper dependencies once
RUN chmod +x mvnw

# Expose app port
EXPOSE 8080

# Default dev command (hot reload if using devtools)
CMD ["./mvnw", "spring-boot:run"]
