networks:
  tms_jar:
    driver: bridge

volumes:
  db_data:

services:
  nginx:
    extends:
      file: docker-compose.yml
      service: nginx

  db:
    extends:
      file: docker-compose.yml
      service: db

  phpmyadmin:
    extends:
      file: docker-compose.yml
      service: phpmyadmin

  spring_app:
    extends:
      file: docker-compose.yml
      service: spring_app
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:  
      - ./:/app
