networks:
  tms_jar:
    driver: bridge

volumes:
  db_data:

services:
  nginx:
    container_name: "${COMPOSE_PROJECT_NAME}-nginx"
    image: cslant/dev-nginx
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./:/app
      - ./docker/logs:/var/log/nginx
    ports:
      - "${NGINX_HOST_HTTP_PORT:-80}:80"
    platform: ${PLATFORM:-linux/amd64}
    environment:
      - SPRING_HOST_PORT=${SPRING_HOST_PORT}
    networks:
      - tms_jar
    depends_on:
      - spring_app
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mysql:8.0.32
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}"
    networks:
      - tms_jar

  spring_app:
    build: .
    container_name: "${COMPOSE_PROJECT_NAME}-spring_app"
    volumes:
      - .:/app
    ports:
      - "${SPRING_HOST_PORT}:5000"
    depends_on:
      - db
    networks:
      - tms_jar

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${COMPOSE_PROJECT_NAME}-phpmyadmin"
    platform: ${PLATFORM:-linux/amd64}
    restart: always
    ports:
      - "${PHPMYADMIN_PORT:-9024}:8380"
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 2048M
    networks:
      - tms_jar
