spring:
  application:
    name: tms-web-service
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/tms
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080